### ISSUE TITLE
Update to 2.5.4

### ISSUE THREAD

**Issue by Iowerth** [OF-Ala/LFGSorter#2]
Hi. Not working well in 2.5.4:
1. Adds a chat frame with both /1 and /4 channels enabled (before 2.5.4 an empty frame created).
2. Sound for selected instances is played but without any words in LFGS or another frame.
3. Button "Delete added frame" not working - not closing early opened frame.

Привет. Не работает нормально в 2.5.4:
1. Добавляет окно чата с одновременно включенными каналами /1 и /4, хотя до 2.5.4 просто пустое окно создавалось.
2. Воспроизводится звук для выбранных инстов, но нигде не отображается текст - ни в LFGS, ни в других окнах.
3. Кнопка "Закрыть созданное окно" не работает - не закрывает ранее открытое окно.

**Comment by Iowerth** [comment]
Any news?

**Comment by OF-Ala** [comment]
Hi!

1. The idea was always like this - create frame with /1 and /4 chats enabled
2. Try updating to 2.0.9.5, mb this was already fixed. If not - show me you settings with selected instances
3. Try new 2.0.9.5 version, tab open/close issue should be fixed there

Привет!

1. Новая вкладка чата должна была всегда создаваться с 1 и 4 каналами, чтобы сразу отображать нужные сообщения
2. Это странно. Если после обновления также - покажи скрин с настройками выбранных инстов
3. Должно быть исправлено в версии 2.0.9.5

**Comment by Iowerth** [comment]
All fixed, thanks!
Спасибо за фикс, теперь всё ок :)
